CI: only run deploy if build actually finished

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -68,6 +68,10 @@ jobs:
             echo "public directory is empty"
             exit 1
           fi
+          if [ ! -f .BUILD_FINISHED ]; then
+            echo ".BUILD_FINISHED not found"
+            exit 1
+          fi
       - uses: actions/upload-artifact@v4
         with:
           name: build-artifact-${{ github. ref_name }}
